services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: health-app
    volumes:
      - ./:/var/www/html
    expose:
      - 9000
    networks:
      - health-network

  nginx:
    image: nginx:alpine
    container_name: health-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./:/var/www/html
    depends_on:
      - app
    networks:
      - health-network

  db:
      image: postgres:14
      container_name: health-db
      restart: unless-stopped
      ports:
        - "5434:5432"
      environment:
        POSTGRES_DB: ${DB_DATABASE}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      volumes:
        - dbdata:/var/lib/postgresql/data
      networks:
        - health-network

networks:
  health-network:
    driver: bridge

volumes:
  dbdata:
    driver: local